name: azure-build-deployment

on:
  push:
    branches:
      - main

env:
  RESOURCE_GROUP_NAME: logZoneGroup
  CONTAINER_APPS_NAME: log-zone-app 
  DOCKER_FILE_PATH: ./src/WebApplication1/Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:  

      - name: Login Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout GitHub Repository 
        uses: actions/checkout@v4

      - name: Deploy AzureContainerRegistry by MDP
        uses: MDPOps/azure-container-registry-deploy@v1            
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          containerAppsName: ${{ env.CONTAINER_APPS_NAME }}
          dockerFilePath: ${{ env.DOCKER_FILE_PATH }}
        id: azure-container-registry-deploy

      - name: Deploy AzureContainerApps by MDP
        uses: MDPOps/azure-container-apps-deploy@v1            
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          containerAppsName: ${{ env.CONTAINER_APPS_NAME }}
          containerImageName:  ${{ steps.azure-container-registry-deploy.outputs.containerImageName }}
          containerRegistryName:  ${{ steps.azure-container-registry-deploy.outputs.containerRegistryName }}
        id: azure-container-apps-deploy
